# specify docker as dependency
# build test version of services
# run tests
# build prod versions of all services
# push all to docker hub
# update host
sudo: required
services:
  - docker

before_install:
  - docker build -t grant05/react-test -f ./client/Dockerfile.dev ./client

script:
  # -- --coverage stops watcher to exit test mode
  - docker run grant05/react-test npm run test -- --coverage

after_success:
  - docker build -t grant05/multi-client ./client
  - docker build -t grant05/multi-nginx ./nginx
  - docker build -t grant05/multi-server ./server
  - docker build -t grant05/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push to docker hub
  - docker push grant05/multi-client
  - docker push grant05/multi-nginx
  - docker push grant05/multi-server
  - docker push grant05/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-1-177328609013
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY